### ISSUE TITLE
Add `resources` Parameters for the Autoscaler Deployment in the Helm Chart

### ISSUE THREAD

**Issue by lorenzophys** [lorenzophys/pvc-autoscaler#12]
Currently, the Helm chart for the PVC autoscaler project does not include `resources` for the deployment manifest.
The schema should be:
```yaml
resources:
    requests:
      cpu: xxxm
      memory: xxxMi
```

## Tasks:

1. Update the values.yaml file to include the `resources` parameter
2. Update the chart template and ensure that these parameters will be templated in the right place
3. Choose reasonable defaults
4. Update the Helm chart version
